### ISSUE TITLE
Add Karma test runner

### ISSUE THREAD

**Issue by frontshift** [nicksp/redux-webpack-es6-boilerplate#13]
It would be nice to add Karma to make debugging easier and give people the flexibility to add adapters, frameworks, coverage reporters etc and use different browsers.

**Comment by nicksp** [comment]
@WanjaStier Hey, that's actually in my todo list :) Thanks for reminding.
Will look into it soon.

**Comment by nicksp** [comment]
@WanjaStier If you don't mind, closing that issue, since i'm working on a big update to the boilerplate, which hopefully will be released soon which will address what you've mentioned. 

You can check what's going to be new in [here](https://github.com/nicksp/redux-webpack-es6-boilerplate/blob/master/README.md)
