### ISSUE TITLE
Fonts not showing up on development server

### ISSUE THREAD

**Issue by carmouche** [nicksp/redux-webpack-es6-boilerplate#20]
Hello,

I realized while using this boilerplate that I couldn't get the fonts to work correctly when running the webpack dev server.  The demo doesn't seem to be rendering the Open Sans font.  I haven't checked if the fonts are working in the production build.  I played around with the config and using different paths but couldn't get it working :(  Maybe you can help!!  

Thanks!

**Comment by ifranke** [comment]
Same issue. As previous posted a guess, the problem is the ''url(./path-to-hashed-font)" in Font-Face definition.  Solved in first try by changing the loader for .woff to file-loader and force the output in webpack def to "http:/localhost:<yourdevport>". Problem is the url-loader which creates relative urls and with the style-loader your resulting .css with your font-face url is in a blob where the font-file naturally is not included... 

Really ugly hack for dev only.

So in short:

output: {
    path: PATHS.build,
    filename: 'js/bundle.js',
    publicPath: 'http://localhost:3001/' // development only
  },
...

module: {
    loaders: [
      ...
      {
        test: /.woff2?(\?v=[0-9].[0-9].[0-9])?$/,
        //loader: 'url-loader?limit=10000&name=[name]-[hash].[ext]&mimetype=application/font-woff'
        loader: 'file-loader'
      },
...

Issue should be also solved, if you use extract-text-webpack-plugin as demonstrated for production build, but I do not know which issues you will have in hot reloading if you change this in dev...

**Comment by posti85** [comment]
Just setting the `publicPath` in the `devServer` property also worked for me and it is cleaner :)

    devServer: {
        contentBase: 'www/',
        publicPath: 'www/',
        open: true
    }

**Comment by rflmyk** [comment]
+1
